[project]
name = "picocontroller2mnk"
version = "0.2.4"
description = ""
authors = [
    {name = "Xiaode2333",email = "Xiaode2333@users.noreply.github.com"}
]
requires-python = "^3.12"
dependencies = [
    "pyserial (>=3.5,<4.0)",
    "pynput (>=1.7.8,<2.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
